const checklists = [
    'Aliyun Linux',
    'AlmaLinux OS',
    'Amazon Linux',
    'Amazon Web Services',
    'Apache Cassandra',
    'Apache HTTP Server',
    'Apache Tomcat',
    'Apple iOS',
    'Apple macOS',
    'Azure Linux',
    'BIND',
    'Bottlerocket',
    'CentOS Linux',
    'CheckPoint Firewall',
    'Cisco',
    'Debian Family Linux',
    'Debian Linux',
    'Distribution Independent Linux',
    'Docker',
    'F5',
    'Fedora Family Linux',
    'Fortinet',
    'Google Android',
    'Google Cloud Computing Platform',
    'Google Workspace',
    'IBM AIX',
    'IBM Cloud Foundations',
    'IBM Db2',
    'IBM i',
    'IBM WebSphere',
    'IBM Z System',
    'Juniper',
    'Kubernetes',
    'MariaDB',
    'Microsoft 365',
    'Microsoft Azure',
    'Microsoft Dynamics 365 Power Platfrom',
    'Microsoft Exchange Server',
    'Microsoft IIS',
    'Microsoft Intune for Microsoft Windows',
    'Microsoft Office',
    'Microsoft SharePoint',
    'Microsoft SQL Server',
    'Microsoft Web Browser',
    'Microsoft Windows Desktop',
    'Microsoft Windows Server',
    'MIT Kerberos',
    'MongoDB',
    'Mozilla Firefox',
    'NGNIX',
    'Oracle Cloud Infrastructure',
    'Oracle Database',
    'Oracle Linux',
    'Oracle MySQL',
    'Oracle Solaris',
    'Palo Alto Firewall',
    'pfSense Firewall',
    'PostgreSQL',
    'Print Devices',
    'Red Hat Enterprise Linux',
    'Robot Operating System',
    'Rocky Linux',
    'Safari Browser',
    'Snowflake',
    'Software Supply Chain Security',
    'Sophos',
    'SUSE Linux Enterprise Server',
    'Ubuntu Linux',
    'VMware',
    'YugabyteDB',
    'Zoom',
    // Add more checklist names as needed
];


export default checklists;
